lortza/therapy_tracker

.travis.yml, Gemfile, Gemfile.lock, app/views/reports/index.html.erb, db/seeds.rb, spec/factories/exercise_log.rb, spec/factories/exercises.rb
Closes #15 
The seeds files was getting out of date as compared to the models. For example, I've added new fields and also done a couple of name changes. The seeds file was falling behind because it had to be updated manually. Also, color me lazy, but it was getting tedious to come up with realistic-looking timeframes for each of the logs. 
I moved as much logic as I could into factories. Since factories need to be updated in order to keep tests up to date, this is an automatic win for  updating the seeds as a byproduct. Adding in `Faker`'s `Date` module give us access to a lovely assortment of dates for when logs occur. I foresee this setup being much more scalable and easier to maintain.
=> 15 Replace redundant seed data with times.do loops and Faker dates

app/controllers/pt_sessions_controller.rb, app/helpers/pt_sessions_helper.rb, app/models/exercise.rb, app/models/pain_log.rb, app/models/pt_session.rb, app/models/pt_session_exercise.rb, app/views/pt_sessions/_form.html.erb, app/views/pt_sessions/show.html.erb, db/migrate/20190426010827_add_stats_to_pt_session_exercises.rb, db/schema.rb, db/seeds.rb, spec/factories/pain_logs.rb, spec/factories/pt_session_exercises.rb, spec/models/exercise_spec.rb, spec/models/pain_log_spec.rb, spec/models/pt_session_exercise_spec.rb, spec/models/pt_session_spec.rb
Previously, we could only add a simple exercise name to a physical therapy log in order to indicate the exercises done in that session. Like so:
That's handy, but I wanted to track the progress of these exercises at each session. In order to do that, i needed to track more stats. I added details to the `pt_session_exercises` model in order to capture that information, like so:
This work involved a migration to add new fields and also changing up the associations a little bit. There is what looks like more redundancy in some of the exercise stat display helpers and some tables, but i think it's still fine at this point. If we expand more, we may want to look into polymorphism to consolidate exercise data.
@kelseyhuse30, want to review this PR?
=> Add stats to pt session exercises

.travis.yml, spec/controllers/body_parts_controller_spec.rb, spec/controllers/exercise_logs_controller_spec.rb, spec/controllers/exercises_controller_spec.rb, spec/controllers/pain_logs_controller_spec.rb, spec/controllers/pains_controller_spec.rb, spec/controllers/physical_therapy_sessions_controller_spec.rb, spec/rails_helper.rb
This should get all the controller tests passing for now, although there are some pending tests that can be tackled later on.
I used the login_user method at the start of all controllers in order to generate a current_user which makes these requests now valid.  The [devise docs](https://github.com/plataformatec/devise/wiki/How-To:-Test-controllers-with-Rails-(and-RSpec)#rails-3-rspec-scaffolds) recommended removing the `valid_session` boilerplate that rspec generates, since Devise has their own methods.
=> get controller tests passing

app/assets/javascripts/exercises.js, app/assets/stylesheets/_variables.scss, app/assets/stylesheets/buttons.scss, app/assets/stylesheets/exercises.scss, app/assets/stylesheets/logs.scss, app/assets/stylesheets/rep_counter.scss, app/assets/stylesheets/shared.scss, app/models/exercise.rb, app/views/exercises/index.html.erb
Closes #29 
Secondary information is now hidden behind the exercise name. This info can be seen by toggling the arrow on the right side.
=> 29 exercise index

app/assets/javascripts/exercises.js, app/assets/javascripts/pain_logs.js, app/models/pain.rb, app/views/exercise_logs/new.html.erb, app/views/pain_logs/_form.html.erb, app/views/pain_logs/new.html.erb, spec/models/pain_spec.rb
This adds some JS assistance to the pain logs form so that fields are populated when a person enters a "none" entry for pain. Since `pain`s are user-generated, it is not guaranteed that every use will have a "none" `pain`. It's fine with me to have this as sort of an easter egg feature. Also, since i am my only user, i want to make this easy for myself to use.
=> Facilitate pain log data entry

app/helpers/logs_helper.rb, app/models/body_part.rb, app/models/exercise.rb, app/models/pain.rb, app/views/body_parts/index.html.erb, app/views/body_parts/new.html.erb, app/views/devise/registrations/new.html.erb, app/views/exercises/index.html.erb, app/views/logs/_new_user_welcome.html.erb, app/views/logs/index.html.erb, app/views/pains/index.html.erb, app/views/pains/new.html.erb, spec/models/body_part_spec.rb, spec/models/exercise_spec.rb, spec/models/pain_spec.rb
Closes #55 
When a new user signs up, the welcome page is empty:
Create content to guide a user through setting up the necessary data and getting started. When a user has not set up `pains`, `exercises`, or `body_parts`, these sections appear, prompting them to do so:
Once a user has set up those 3 pieces of data, those parts of the view go away and they are prompted to make a new log. 
Once a user logs _anything_ this content goes away and they get to see their logs.
=> 55 landing page content

app/assets/stylesheets/_variables.scss, app/assets/stylesheets/forms.scss, app/assets/stylesheets/search_bar.scss, app/assets/stylesheets/shared.scss, app/controllers/body_parts_controller.rb, app/models/body_part.rb, app/views/body_parts/_form.html.erb, app/views/body_parts/index.html.erb, app/views/exercise_logs/_form.html.erb, app/views/exercises/_form.html.erb, app/views/pain_logs/_form.html.erb, app/views/pains/_form.html.erb, app/views/pt_sessions/_form.html.erb, db/migrate/20190601235732_add_active_to_body_parts.rb, db/schema.rb, spec/factories/body_parts.rb, spec/models/body_part_spec.rb, spec/models/exercise_log_spec.rb, spec/models/exercise_spec.rb, spec/models/pain_log_spec.rb, spec/models/pain_spec.rb, spec/models/pt_homework_exercise_spec.rb, spec/models/pt_session_spec.rb, spec/models/user_spec.rb
Closes #71 
Sometimes a user has too many body parts in dropdowns for past injuries. It would be nice to make those go away without having to delete them.
- Add an "archived" boolean to the body parts form
- limit the body parts that appear in dropdown to only "active" body parts
- added html "required" attribute to required fields
- made form label styles prettier
- organized stylesheets 
- added better testing for expected attributes to model specs
=> 71 active inactive body parts

app/controllers/reports_controller.rb, app/models/report.rb
Trying to resolve this complexity error.
Rubocop said my initialize was too complex. It was, so I moved it out into another method. That method now has too many lines. I'm not worried about that.
I would like to reduce the querying made by the `reports` page. This is why I memoized the `@report` instance variable. But now Rubocop says memoizing isn't cool and that `@report` should be `@index`. This is crazytalk, Rubocop.
=> 53 rubocopping spike refactor

app/helpers/reports_helper.rb, app/models/pain_log.rb, app/views/stats/_body_part_table.html.erb, spec/helpers/reports_helper_spec.rb, spec/models/pain_log_spec.rb, spec/rails_helper.rb
There was a conflict with methods and active record relations being named the same thing that was causing confusion (certainly mine) and probably within the code as well. It was causing the collection of log occurrences to include more than what was in the group when searching for the first and last occurrence.
Any Pain Type that was used for more than one body part was including occurrences for other body parts in the results. This is why what looked like 1 occurrence had two different dates for first and last occurrence.
=> Fix activerecord collision with occurrence ordering

app/models/occurrence_calculator.rb, app/views/shared/_session_nav.html.erb, app/views/stats/index.html.erb
The multi-part `if` statement I was using in the method to calculate timeframe for pain data was clunky. After pairing with @flylady2, we chose to convert it to a case statement. In the process, we also renamed a variable and now the method is much easier to read. 🙌 
While I was working on this page, I also clarified the heading and nav bar item by adding the word "pain".
=> Convert conditional to case statement

app/controllers/slit_logs_controller.rb, app/views/buttons/_new_slit_log.html.erb, app/views/shared/_session_nav.html.erb, config/routes.rb, spec/requests/slit_logs_spec.rb
* There was a params problem where quick logging worked just fine, but adding from a new form (via traditional new/create) was not picking up the controller values. 
* this pr fixes that bug and adds specs for the new controller action
=> Separate regular slit logging from quick logging

app/assets/stylesheets/_variables.scss, app/assets/stylesheets/slit.scss, app/controllers/slit_logs_controller.rb, app/views/slit_logs/report.html.erb, config/routes.rb
Closes #759
* basic table-looking printout view that mimics the paper table provided for manual logging
* prints in 3 columns
* includes "new bottle" indication
* mobile styles
* prints all records for the past 90 days (a typical SLIT feedback window)
* doing a cmd +p from the browser lets you print the data in a printer-friendly way
* displaying "skipped" doses in the printout
* allowing for dynamic reporting between user-provided dates
* css `columns` is a really handy way to make content from through columns like a newspaper layout
=> Make basic print view to take to dr

Procfile
* Adds a production Procfile that has been missing
* Adds migrations to the heroku release phase
* Heroku has a release phase that allows you to run commands after merge and before deploy https://mentalized.net/journal/2017/04/22/run-rails-migrations-on-heroku-deploy/
* Heroku docs https://devcenter.heroku.com/articles/release-phase
=> Add prod procfile with migrations

.github/pull_request_template.md, app/assets/stylesheets/_variables.scss, app/assets/stylesheets/logs.scss, app/views/exercise_logs/_exercise_log_header.html.erb, app/views/pain_logs/_pain_log_header.html.erb, app/views/pt_session_logs/_pt_session_log_header.html.erb, app/views/slit_logs/_slit_log.html.erb, app/views/slit_logs/_slit_log_header.html.erb, app/views/slit_logs/_slit_log_skipped_dose_header.html.erb, app/views/slit_logs/report.html.erb, db/migrate/20240317143500_add_dose_skipped_to_slit_logs.rb, db/migrate/20240317151929_add_enable_slit_tracking_to_user.rb, db/schema.rb, spec/factories/slit_logs.rb, spec/factories/users.rb, spec/models/user_spec.rb
Closes #769
Related to #768
Related to #762
* adds skipped column to `slit_logs` table
* adds front end conditional logic to display a day when doses were skipped
* logs index views
* slit printout view
* adds table change for #786
* I needed to separate the css concerns of color from styling into different classes in order to be more clean about style rendering and to avoid collisions
=> Add SLIT therapy back end logic and display logic for "skipped" doses 

app/assets/stylesheets/_variables.scss, app/models/user.rb, app/services/slit_log_skipped_dose_service.rb, lib/tasks/heroku_cron_tasks.rake, spec/models/user_spec.rb, spec/services/slit_log_skipped_dose_service_spec.rb
Closes #771
Closes #762
* When a user skips a SLIT dose, the app populates a "skip" log for them. 
* Users can see doses they've skipped in the views
* Skipped doses appear in the dr printout view
=> Service for logging yesterday's skipped doses

app/assets/stylesheets/_variables.scss, app/assets/stylesheets/logs.scss, app/assets/stylesheets/shared.scss, app/assets/stylesheets/slit.scss, app/assets/stylesheets/utilities.scss, app/controllers/slit_logs_controller.rb, app/models/slit_log.rb, app/services/slit_log_skipped_dose_service.rb, app/views/exercise_logs/_exercise_log.html.erb, app/views/pain_logs/_pain_log.html.erb, app/views/pt_session_logs/_pt_session_log.html.erb, app/views/slit_logs/_slit_log.html.erb, app/views/slit_logs/_slit_log_skipped_dose_header.html.erb, app/views/slit_logs/report.html.erb, config/application.rb, spec/views/exercise_logs/index.html.erb_spec.rb, spec/views/pain_logs/index.html.erb_spec.rb, spec/views/pt_session_logs/index.html.erb_spec.rb
* makes the log type easier to see 
* makes the skipped slit log easier to see
=> Change styling for log entires

app/controllers/users_controller.rb, app/views/shared/_add_log_buttons.html.erb, app/views/shared/_session_nav.html.erb, app/views/users/edit.html.erb, config/routes.rb, spec/requests/users_spec.rb
Closes #768
* now that a user has the option to tun on/off SLIT tracking, we need to give the user the ability to edit that setting
* this PR give the user a form to do that
* also show/hide buttons in the nav conditionally based on whether SLIT tracking is turned on for a person
=> Allow user profile editing

app/controllers/users_controller.rb, app/views/shared/_session_nav.html.erb, app/views/users/edit.html.erb, config/routes.rb, spec/requests/users_spec.rb
* keeps the user id private by keeping it out of the url params for the user profile edit page
=> Move user id out of url params for profile edit

app/components/material_icon_component.rb, app/components/new_log_button_component.rb, app/views/buttons/_new_exercise_log.html.erb, app/views/buttons/_new_pain_log.html.erb, app/views/buttons/_new_pt_session_log.html.erb, app/views/buttons/_new_slit_log.html.erb, app/views/exercise_logs/index.html.erb, app/views/logs/_log_component.html.erb, app/views/logs/_log_header.html.erb, app/views/pain_logs/index.html.erb, app/views/pt_session_logs/index.html.erb, app/views/shared/_add_log_buttons.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_search_form.html.erb, app/views/slit_logs/index.html.erb
Closes #791
* renames `MaterialIcon` to `MaterialIconComponent` to embrace its componenty nature
* crates new `NewLogButtonComponent`
* each log type had its own partial for a button that is used on the home index page as well as each respective log indexes
* the new component takes a log class and builds a "new log" button for that class
* leverages rails magic plus decorator data to build custom buttons automagically
=> Convert button partials to button components

app/controllers/users_controller.rb, app/views/pt_session_logs/index.html.erb, app/views/shared/_add_log_buttons.html.erb, app/views/shared/_session_nav.html.erb, app/views/users/edit.html.erb, db/migrate/20240331195553_add_enable_pt_session_tracking_to_users.rb, db/schema.rb, spec/factories/users.rb, spec/models/user_spec.rb
* if a user is not currently doing physical therapy, they do not need a button to log a session
* adds config to user settings to enable/disable pt session tracking
* conditionally displays "add" buttons based on config
* config set to "false" by default
* this is heckin easy to do since i aldrad did it for slit tracking. i think i banged this out in 8 minutes.
=> Add enable_pt_session_tracking to users

app/helpers/logs_helper.rb, app/views/slit_logs/_slit_log.html.erb, spec/helpers/logs_helper_spec.rb
* since the app is on pooled dynos, it is sometimes hard to tell if the quick log worked.
* i don't always know the date first thing in the morning
* this PR replaces the date with "today" when the log date is today
=> Add today to slit logs

app/assets/stylesheets/pagination_links.scss, app/controllers/slit_log_reports_controller.rb, app/controllers/slit_logs_controller.rb, app/models/slit_log.rb, app/models/slit_log_report.rb, app/models/user.rb, app/views/shared/_session_nav.html.erb, app/views/slit_log_reports/index.html.erb, app/views/slit_log_reports/new.html.erb, config/routes.rb, spec/factories/users.rb, spec/models/user_spec.rb
Closes #812
* allows user to enter custom dates for SLIT log report
* defaults to past 90 days
* displays user full_name instead of just email on SLIT report
* fixes extra space bug on `user.full_name` 
* adds pagination to slit report (with buttons hidden for print)
* `search_params[:start_date].to_date.beginning_of_day` you can only use `beginning_of_day` on a `Date` and not a `DateTime`. also queries didn't work without it.
=> Add start and end dates to SLIT Report

app/assets/stylesheets/utilities.scss, app/controllers/slit_logs_controller.rb, app/views/shared/_add_log_buttons.html.erb, app/views/shared/_quick_log_button_to.html.erb, app/views/shared/_session_nav.html.erb, app/views/slit_logs/index.html.erb
* uses proper `button_to` instead of `link_to` for `post`s made for quick logging 
* creates partial to handle post-style quick logging buttons
* related to #797
* `button_to` is kind of sneaky to style. The `class` arg applies classes to the form `<button>`. The `form_class` arg supplies classes to the form itself.
=> Convert quick logging from link_to to button_to

app/services/slit_log_skipped_dose_service.rb, config/application.rb, spec/services/slit_log_skipped_dose_service_spec.rb, spec/views/pain_logs/show.html.erb_spec.rb
* fixes a bug where after upgrading to ruby 3.2.2 and rails 7.1 that the time zone for logging was not displaying correctly.
=> Set app time zone

app/assets/stylesheets/slit.scss, app/controllers/slit_logs_controller.rb, app/views/exercise_logs/_rep_counter_modal.html.erb, app/views/exercise_logs/show.html.erb, app/views/logs/index.html.erb, app/views/shared/_add_log_buttons.html.erb, app/views/shared/_session_nav.html.erb, app/views/slit_logs/quick_log_create.js.erb
Closes #797
* Allows for 1-touch logging and timer start
* No need for setting an external timer
* Sounds chime at end of timer for when you're not looking at your phone
* Allows for dismissing the timer early
* Allows for dismissing the timer when the timer has finished
=> Add automatic countdown timer for slit quick dose

app/views/logs/index.html.erb
* only displays PT homework on logs index if the user has enabled PT session logging
* only displays SLIT timer on logs index if the user has enabled SLIT logging
* cleans up the html output and reduces opportunity for trying to query on `nil`
=> Put SLIT and PT features behind user settings

app/assets/stylesheets/slit.scss
* gives a little more visibility to a skipped SLIT dose in the print media query
=> Outline and margin on dose skipped

app/views/devise/registrations/edit.html.erb, app/views/devise/sessions/new.html.erb, config/routes.rb
* disables user sign-up ability. this had been turned on because i had wanted access to the other devise registrations routes
* fancies up the devise sign in and edit settings pages with bootstrap styles
* how to clobber a single devise route
=> Disable user sign-up

app/controllers/slit_logs_controller.rb, app/models/slit_log.rb, app/views/shared/_session_nav.html.erb, spec/models/slit_log_spec.rb
Closes #755
* indicates how many doses are left in the current bottle
* uses existing view logic
* allows user-entered value to persist (for backfilling purposes or non-standard bottle amts)
* sets value to default value when there is a new bottle
* adds new quick link for quick log with new bottle
Passing params with a create path helper is not intuitive:
```
button_to 'SLIT dose New Bottle', quick_log_create_path, params: {started_new_bottle: true}, method: :post, remote: true, class: 'dropdown-item' if current_user.enable_slit_tracking?
```
=> Add dose countdown

app/views/slit_log_reports/index.html.erb, db/seeds.rb, lib/tasks/seed/slit_logs.rake
* The "CALL" indicator was not useful on the report, so i removed it
* Converts AM/PM to am/pm to make it easier to read
* adds seeds for slit logs to make browser testing this feature easier
=> Remove "call" details from slit report

app/controllers/slit_log_reports_controller.rb, app/views/slit_log_reports/index.html.erb
* pagination on the SLIT report for print makes the numbers reset when going to page 2. This is inaccurate and annoying.
* leaves pagination code in place in case i have immediate regrets
=> Comment out pagination for SLIT reports

db/seeds.rb, lib/tasks/seed/exercise_logs.rake, lib/tasks/seed/pain_logs.rake, lib/tasks/seed/pt_session_logs.rake, lib/tasks/seed/slit_logs.rake
* Allows for running of segments of seeds file by running individual tasks like `rake db:seed:slit_logs`
* Can run all seeds with `rake db:seed` as normal
* Is mostly idempotent, but not quite. It does find-or-create for some items but destroys others
* Makes seeds file tidier by separating logging seeds into own task files
* Full seed idempotency is tricky. Depending on whether you plan to run seeds on a clean db or an existing one means different things. Planning for both adds complexity.
=> Separate seeds
