lortza/therapy_tracker

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/logs.scss
- app/assets/stylesheets/shared.scss
- app/controllers/exercise_logs_controller.rb
- app/controllers/logs_controller.rb
- app/controllers/pain_logs_controller.rb
- app/controllers/pt_sessions_controller.rb
- app/views/exercise_logs/index.html.erb
- app/views/logs/index.html.erb
- app/views/pain_logs/index.html.erb
- app/views/pt_sessions/_pt_session.html.erb
- app/views/pt_sessions/index.html.erb
- app/views/pt_sessions/new.html.erb
- app/views/shared/_session_nav.html.erb
- config/initializers/array_paginate.rb
- db/seeds.rb
I was loading all logs on the log main log index page. Over time, loading became slower because there are now a lot of records. I've added pagination button/links for the log index pages. Huzzah.
@kelseyhuse30, want to review this PR?
> 18 add pagination

- app/assets/stylesheets/shared.scss
- app/controllers/exercises_controller.rb
- app/models/exercise.rb
- app/views/exercises/index.html.erb
- spec/models/exercise_spec.rb
Closes #20 
adds a search bar to the exercises index page
> 20 add exercise search

- app/controllers/reports_controller.rb
- app/models/exercise.rb
- app/models/exercise_log.rb
- app/models/pain_log.rb
- app/models/pt_session.rb
- app/views/reports/_report_dropdown.html.erb
- app/views/reports/index.html.erb
- app/views/reports/past_two_weeks.html.erb
- app/views/reports/past_week.html.erb
- app/views/shared/_session_nav.html.erb
- config/routes.rb
> Add reporting for past week and 2 weeks

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/logs.scss
- app/assets/stylesheets/shared.scss
- app/controllers/exercise_logs_controller.rb
- app/views/exercise_logs/_exercise_log.html.erb
- app/views/exercise_logs/_exercise_log_header.html.erb
- app/views/exercise_logs/edit.html.erb
- app/views/exercise_logs/new.html.erb
- app/views/exercise_logs/show.html.erb
- app/views/pain_logs/_pain_log.html.erb
- app/views/pain_logs/_pain_log_header.html.erb
- app/views/pain_logs/edit.html.erb
- app/views/pain_logs/new.html.erb
- app/views/pain_logs/show.html.erb
- app/views/pt_sessions/_pt_session.html.erb
- app/views/pt_sessions/_pt_session_header.html.erb
- app/views/pt_sessions/edit.html.erb
- app/views/pt_sessions/new.html.erb
- app/views/pt_sessions/show.html.erb
> 37 log headers

- README.md
Thought it would be nice to include a few instructions on getting started!
> include dev setup instructions in README

- .travis.yml
Associated with #53 
Enables rubocop to run in CI
> Enable rubocop

- app/controllers/logs_controller.rb
- app/models/concerns/log.rb
- spec/models/log_spec.rb
Move controller logic into module so that it can be unit tested. Hooray!
> Move controller logic into module

- app/assets/javascripts/pain_logs.js
- app/models/concerns/log.rb
- app/models/exercise_log.rb
- app/views/exercise_logs/_form.html.erb
- app/views/pain_logs/_form.html.erb
- app/views/pt_sessions/_form.html.erb
- app/views/pt_sessions/show.html.erb
- spec/models/exercise_log_spec.rb
> 63 remove clearing

- Gemfile
- Gemfile.lock
> Add autoprefixer gem

- .travis.yml
- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
- spec/requests/body_parts_spec.rb
- spec/requests/exercise_logs_spec.rb
- spec/requests/exercises_spec.rb
- spec/requests/pain_logs_spec.rb
- spec/requests/pains_spec.rb
- spec/requests/pt_sessions_spec.rb
Related to #7 
Write specs for the requests specs
> 7 Write request specs

- .rubocop.yml
- .travis.yml
- Gemfile
- Gemfile.lock
- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/buttons.scss
- app/assets/stylesheets/forms.scss
- app/assets/stylesheets/logs.scss
- app/assets/stylesheets/pagination_links.scss
- app/assets/stylesheets/pt_sessions.scss
- app/assets/stylesheets/rep_counter.scss
- app/assets/stylesheets/search_bar.scss
- app/assets/stylesheets/shared.scss
- app/channels/application_cable/channel.rb
- app/channels/application_cable/connection.rb
- app/controllers/reports_controller.rb
- app/helpers/exercise_logs_helper.rb
- app/models/body_part.rb
- app/models/exercise.rb
- app/models/exercise_log.rb
- app/models/pain.rb
- app/models/report.rb
- app/views/pains/_form.html.erb
- app/views/shared/_search_form.html.erb
- spec/models/exercise_spec.rb
- spec/models/pain_spec.rb
Closes #53 
This finishes off the last changes required to get the codebase up to rubocop's spec.
> 53 finalize rubocop changes

- .travis.yml
- app/views/exercise_logs/edit.html.erb
- spec/factories/pt_sessions.rb
- spec/views/exercise_logs/edit.html.erb_spec.rb
- spec/views/exercise_logs/index.html.erb_spec.rb
- spec/views/exercise_logs/new.html.erb_spec.rb
- spec/views/exercise_logs/show.html.erb_spec.rb
- spec/views/pain_logs/edit.html.erb_spec.rb
- spec/views/pain_logs/index.html.erb_spec.rb
- spec/views/pain_logs/new.html.erb_spec.rb
- spec/views/pain_logs/show.html.erb_spec.rb
- spec/views/pt_sessions/edit.html.erb_spec.rb
- spec/views/pt_sessions/index.html.erb_spec.rb
- spec/views/pt_sessions/new.html.erb_spec.rb
- spec/views/pt_sessions/show.html.erb_spec.rb
This is a WIP but I'm opening the PR to get things moving.
> Get view specs running

- .circleci/config.yml
> Try this circleci config

- app/controllers/pain_logs_controller.rb
- app/helpers/logs_helper.rb
- app/models/pain_log.rb
- app/views/pain_logs/index.html.erb
Add filtering form to top of pain logs page. This is a quick feature that i am rolling out so i can do some reporting for doctors. This code is not pretty. It is fast. That's not my favorite, but i want this feature right now. I can polish is later if i want to expand it.
> Add pain log filter by type

- .github/pull_request_template.md
- .rubocop.yml
- app/assets/stylesheets/forms.scss
- app/controllers/pain_logs_controller.rb
- app/helpers/logs_helper.rb
- app/models/pain_log.rb
- app/views/pain_logs/index.html.erb
I did this original work very quickly. I didn't have any prompts for the dropdowns and the code for those dropdowns was pretty janky. This PR:
* uses `id`s for the pains and body parts instead of searching by name
* uses a `prompt` instead of an empty array item
* expands the text search to both `description` and `trigger` fields
Before: No prompts
After: prompts, better button coloring, moved important fields to top.
* passing in a param in the select tag is what lets the field know what option has been selected. Otherwise, you'll jut get the item on the top of the list, or the "prompt".
> Search all descriptions

- app/helpers/reports_helper.rb
- app/models/occurrence_calculator.rb
- app/views/stats/_body_part_table.html.erb
- spec/helpers/reports_helper_spec.rb
- spec/models/occurrence_calculator_spec.rb
* Adds more reporting metrics to facilitate context for doctors, including:
* timeframe
* average frequency
* Something is missing in my rails version or rspec version and i don't have access to `freeze time`. I have some investigating to do on that front.
> Add more stats to table

- app/views/pain_log_quick_form_values/_form.html.erb
- app/views/pain_log_quick_form_values/edit.html.erb
- app/views/pain_log_quick_form_values/index.html.erb
- app/views/pain_log_quick_form_values/new.html.erb
- app/views/shared/_session_nav.html.erb
This PR refines some of the language around quick logging for pains. It also renders the quick logging dropdown conditionally.
> Edit language around quick logging

- app/views/shared/_session_nav.html.erb
* Add the navbar link to the SLIT report
> Add SLIT print report to nav

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/logs.scss
- app/assets/stylesheets/shared.scss
- app/assets/stylesheets/slit.scss
- app/controllers/slit_logs_controller.rb
- app/views/slit_logs/report.html.erb
* adjusts some styles on the SLIT dr report so it fits on 1 letter page better
> Slit report improvements

- app/assets/stylesheets/_variables.scss
- app/assets/stylesheets/logs.scss
- app/assets/stylesheets/utilities.scss
- app/views/exercise_logs/_exercise_log.html.erb
- app/views/pain_logs/_pain_log.html.erb
- app/views/pt_session_logs/_pt_session_log.html.erb
- app/views/slit_logs/_slit_log.html.erb
* makes classes more flexible
* allows log colors to be applied dynamically through interpolation
> Refactor styles

- spec/components/new_log_button_component_spec.rb
Closes #795
* i shipped the new button component w/o specs because i wanted to move fast and feel happy this weekend
* this PR backfills those specs
> Add specs for new button component

- config/initializers/sentry.rb
* I was curious about performance, so I'm setting up sentry performance tracking: https://docs.sentry.io/platforms/ruby/guides/rails/performance/
> Add sentry performance tracking

- config/initializers/sentry.rb
* This _should_ complete the sentry performance tracking setup. We'll see.
> Enable tracing

- app/models/dummy_record.rb
- db/migrate/20240409222940_create_dummy_records.rb
- db/schema.rb
- lib/tasks/heroku_cron_tasks.rake
* gives me a db table and model for testing strange things in prod
> Add DummyRecord model for testing

- app/services/slit_log_skipped_dose_service.rb
- db/migrate/20240410013052_add_data_to_dummy_records.rb
- db/schema.rb
Adds column and logging to rake task
> Add data jsonb to dummy_records
